### ISSUE TITLE
Tab does not appear when you scroll

### ISSUE THREAD

**Issue by sevenstarhope** [pixel-cookers/redmine-theme#22]
Tab under the tab is not visible on the left is more

**Comment by mguo163** [comment]
I also encountered this problem.

**Comment by null12** [comment]
The same problem. When there are a lot of tabs on the left, it's impossible to reach the most bottom ones.

**Comment by kiorpesc** [comment]
To clarify the above comments...

On computer screens with a lower resolution (laptop 1366x768, for example), the bottom-most button(s) in the sidebar are unreachable, because they cannot be scrolled to.  This can be shown by simply resizing a browser window until some buttons are covered, and then attempting to scroll to them.

This issue is present in Chrome, Firefox, and IE.

**Comment by nick7ikin** [comment]
here is a screenshot (sorry for russian titles)

![screenshot](https://f.cloud.github.com/assets/1247707/1631050/19cf5efe-575a-11e3-8dbd-4ed98632e6c8.jpg)

**Comment by sevenstarhope** [comment]
thank you.
fix this.
